action.yml
This PR and repo serves to consolidate all the distributed release workflows for the `prepare` step:
- https://github.com/getsentry/sentry/blob/ca11465cd4d9c1613ed232a313999bf8f3249272/.github/workflows/release.yml#L33-L63
- https://github.com/getsentry/snuba/blob/77a6bbfc892c442e3a2230ca20cc6bcc5e2620ce/.github/workflows/release.yml#L32-L57
- https://github.com/getsentry/relay/blob/24b85242f914454bd18b744c73e71c91bc572ca8/.github/workflows/release.yml#L33-L61
Notable changes:
1. Omits the `killswitch` part as that is reserved for publishing, not prepare
2. Omits the dry-run mode as that is reserved for publishing, not prepare
3. Uses `GIT_` env variables and `EMAIL` env variable as `git config` does not persist for all cases (see …
=> feat(action): Add the first version of generic release action

action.yml
Just learned about this: https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#defaultsrun
=> ref: use defaults for common `shell` value

action.yml
This PR bundles the 'Craft Prepare' and 'Request publish' steps by leveraging the fact that Craft can be run outside of the Docker image, w/o the Craft action as done in getsentry/sentry-javascript#3130. It also improves the automatically crated publish request issue's body by adding the comparison link, normally produced by Craft and tagging the initiator/requester of the release.
~~This PR **SHOULD NOT** be merged before pinning all dependents of `action-prepare-release` as it is very likely to break them.~~
This action now requires `action/checkout` to be run beforehand.
=> feat: Run Craft outside of Docker and bundle publish request 

action.yml
Fixes the composite action and moves all GitHub related interactions to use `gh`, the GitHub CLI (from github-script, which we cannot use in composite actions, and from random `curl` uses)
See https://github.com/getsentry/craft/runs/1655756201?check_suite_focus=true for more context.
=> fix: Fix missing shell param, invalid uses param

action.yml
Some repos, such as [getsentry/sentry-ruby](https://github.com/getsentry/sentry-ruby) run Craft in subfolders. This patch makes the release prepare action support these kinds of flows.
=> feat: Add path option

action.yml
We were using the latest 'release name' instead of the latest 'release _tag_ name' when generating the compare link. These are usually the same but for some cases, like getsentry/publish#90, they can be different and break the MD syntax along with the link.
=> fix(compare): Compare link should use `tag_name`

action.yml
The target creation snippet had an extra `\`, and the duplicate issue checker was referencing a non-existent `$subdirectory` variable due to a c/p error.
=> fix: Fix errors introduced in previous 2 PRs

action.yml
The previous commit, 44a8c6e4e169cda7e4c95d434e7b388e2c7c1fe7 did not fix the issue as Craft's JSON output itself has new lines in it. This patch just uses the multi-line escaping recommended at https://github.community/t/set-output-truncates-multiline-strings/16852/3?u=byk
=> fix(targets): Use newline escaping for targets

action.yml
This switches from using `npm` to install `craft` to directly downloading the single-file binary. This should speed up the craft install and reduce the complexity around installing it (no more temp dir or path modification etc.)
=> feat: Use craft single-file binary

action.yml
We bump our month part of the releases on or after 15th of every month. The auto calver mechanism here was not aware of that and now it is with this patch.
=> fix(calver): Fix auto calver as we do releases on 15th

action.yml
As this is a bash script, backticks are interpreted as a command, making their content missing, eg. https://github.com/getsentry/publish/issues/887#issue-1158702634
=> Fix escaping of #retract comment

action.yml
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Committed via https://github.com/asottile/all-repos
=> ref(ci): fix set-output / set-state deprecation

action.yml
from checking out a release branch:
```bash
GITHUB_OUTPUT=output
git checkout origin/HEAD -b release-whatever
git commit --allow-empty -m test
echo "branch=$(git rev-parse --symbolic-full-name HEAD)" >> "$GITHUB_OUTPUT"
echo "sha=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"
echo "last=$(git rev-parse --verify "$(git describe --tags --abbrev=0)" || echo HEAD)" >> "$GITHUB_OUTPUT"
cat "$GITHUB_OUTPUT"
```
```console
$ bash -x t.sh 
+ GITHUB_OUTPUT=output
+ git checkout origin/HEAD -b release-whatever
Branch 'release-whatever' set up to track remote branch 'main' from 'origin'.
Switched to a new branch 'release-whatever'
+ git commit --allow-empty -m test
[release-whatever 73e14d4] test
++ git rev-parse --symbolic-full-name HEAD
+ echo branch=refs/heads/release-whatever
++ git rev-parse HEAD
+ …
```
=> use the previous tag from git history rather than github

action.yml
GITHUB_OUTPUT doesn't support the (undocumented) %0A hack
tested here: https://github.com/asottile-sentry/test-plz-ignore/actions/runs/3242877246/jobs/5316785720
=> fix multiline output variable

action.yml
the original approach of preventing `craft` from switching did not work -- trying this approach instead
=> ref: switch back to release branch for git info

action.yml
This PR adds a new optional input to the Prepare Release Action: `craft_config_from_merge_target`
If this option is set to `true`, the craft config for preparing the release and reading the targets from will be taken from the merge target branch (if specified) instead of from the default branch. 
By default, we keep the current behaviour, meaning craft checks out the default branch after `craft prepare` and we read the targets from the config of the default branch. 
tested run showing that the craft config is actually taken from the merge target branch: https://github.com/getsentry/publish/issues/3421
This PR is part 1 of making it possible to take the craft config from the merge target branch instead of the default branch. This will allow us to maintain multiple major versions and have …
=> feat: Add option to use craft config from merge target branch to prepare release

action.yml
Small optimization PR for the new (optional) behaviour added in #34:
- use `--depth 1` as suggested in https://github.com/getsentry/action-prepare-release/pull/34#discussion_r1491743716
- avoid fetching the second time we check out the branch (not necessary, since we're in the same job anyway)
ref https://github.com/getsentry/publish/issues/3441
=> ref: Optimize merge target branch checkout step

action.yml
In the `release-git-info` step, we previously always checked out the previous branch (`git checkout -` which TIL is a shorthand for `git checkout @{-1}`). However, if action users opted into checking out the merge target branch (`craft_config_from_merge_target`), we make an additional checkout between `craft prepare` and `release-git-info`, causing us to go back only to the merge target branch instead of the release target branch.
The consequences were that the "View Changes" and "View check runs" links were incorrect. AFAICT there were no "more serious" implications as this had no effect on the actual publishing part.
This PR changes the behaviour to checkout the second last branch (`@{-2}`) in this case and otherwise, as previously, the last branch. 
Since I don't like this syntax …
=> fix: Correctly switch to release branch when extracting git info

action.yml
When working on #34 I split up the "Craft Prepare" step and missed that we `cd`'d into `inputs.path` in the original step and this was reset once we exited the step. The new "Read Craft Targets" step should also happen in the same `inputs.path` directory but it didn't anymore because the new step was missing the `cd` command.
This PR re-adds moving to the `inputs.path`. As recommended by @asottile-sentry I used the [`working-directory` option](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runsstepsworking-directory) instead of the `cd` command.
=> fix: Restore working directory in "Get Release Info" step

action.yml
Clarify that you must leave a comment only containing retract and nothing else to retract a release.
Related publish PR for updating the tests there https://github.com/getsentry/publish/pull/5533.
=> impr: Clarify how to retract
